package kdr.resume.salestaxes.receipt;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * Messages handling class, auto-generated by Eclipse IDE
 */
public class Messages {
	
	private static final String BUNDLE_NAME = "kdr.resume.salestaxes.receipt.messages"; //$NON-NLS-1$

	private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle
			.getBundle(BUNDLE_NAME);
	
	private Messages() {
	}

	public static String getString(String key) {
		try {
			return RESOURCE_BUNDLE.getString(key);
		} catch (MissingResourceException e) {
			return '!' + key + '!';
		}
	}
}
